# Generated by Django 4.2.20 on 2025-03-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='BotSettings',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
