# Generated by Django 4.2.20 on 2025-03-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socialmediaaccount'),
        ('chat', '0002_remove_subscription_chatbot_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='chat_app',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.socialmediaaccount'),
        ),
    ]
