# Generated by Django 4.2.20 on 2025-03-17 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='App Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='chat_apps/')),
            ],
        ),
        migrations.CreateModel(
            name='ChatBotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ChatBot Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('voice_tone', models.CharField(choices=[('warm', 'Ấm áp'), ('funny', 'Hài hước'), ('cold', 'Lạnh lùng')], default='warm', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('chat_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.chatapp')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatbottype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_apps', models.ManyToManyField(blank=True, related_name='userprofile', to='home.chatapp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatbottype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Chatbot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_speed', models.FloatField(default=1.0)),
                ('personality', models.CharField(choices=[('friendly', 'Thân thiện'), ('romantic', 'Lãng mạn'), ('serious', 'Nghiêm túc')], default='friendly', max_length=50)),
                ('joke_frequency', models.IntegerField(default=3, help_text='Sau bao nhiêu tin nhắn sẽ chèn 1 câu đùa?')),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.chatbottype')),
            ],
        ),
    ]
