# Generated by Django 4.2.20 on 2025-03-17 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_chatsession_chat_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatbottype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_speed', models.FloatField(default=1.0)),
                ('personality', models.CharField(choices=[('friendly', 'Thân thiện'), ('romantic', 'Lãng mạn'), ('serious', 'Nghiêm túc')], default='friendly', max_length=50)),
                ('joke_frequency', models.IntegerField(default=3, help_text='Sau bao nhiêu tin nhắn sẽ chèn 1 câu đùa?')),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.chatbottype')),
            ],
        ),
    ]
