# Generated by Django 4.2.20 on 2025-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socialmediaaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaaccount',
            old_name='password',
            new_name='app_pass',
        ),
    ]
